USE customer_behavior;
SELECT TOP 10 * FROM customer

--Q1 : What is the total revenue generated by male vs female customers ??
SELECT 
gender,
SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY gender

--Q2 : Which Customers used a discount but still spent more than the average purchase amount??
SELECT 
	customer_id,
	purchase_amount
FROM customer
WHERE discount_applied =  'Yes'AND purchase_amount >= (
													SELECT AVG(purchase_amount)
													FROM customer
													)

--Q3 : Which are the Top 5 products with the highest average review rating??

SELECT TOP 5
item_purchased,
ROUND(AVG(review_rating),2) AS 'Review_Rating'
FROM customer
GROUP BY item_purchased
ORDER BY Review_Rating DESC

--Q4 : Compare the avergae Purchases Amounts between Standard and Express Shipping??

SELECT 
shipping_type,
AVG(purchase_amount) AS Avergae_Purchase_Amount
FROM customer
WHERE shipping_type in ('standard', 'Express')
GROUP BY shipping_type

--Avergae Purchcase amount is higher for express shipping rather than standard shipping .  
--The Business Should focus on expressshipping and other fastest delivery options.

--Q6 : Do Subscribed Customers spend more ? Compare average spend and total revenue 
--between subscribers and non - subribers.

SELECT 
COUNT(customer_id) AS 'Total_Customers',
subscription_status,
AVG(purchase_amount) AS 'Average Spent',
SUM(purchase_amount) AS 'Total Spent'
FROM customer
GROUP BY subscription_status

--Q6 : Which 5 Products have the highest percentage of purchases with discounts applied??

SELECT TOP 5
item_purchased,
SUM(100 * CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*)AS 'discount_rate'
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q7 : Segment Customers into New, Returninig, and Loyal based on their total Number of Previous  
--Purchases, and show the count of each segment.

WITH customer_type AS (
SELECT customer_id , previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS 'Number of customer'
FROM customer_type
GROUP BY customer_segment

--Q8 : What are the Top 3 Most Purchased Products Within Each Category

WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS 'total_orders',
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) AS 'item_rank'
FROM customer
GROUP BY category , item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3

--Q9 : Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe??

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer 
WHERE previous_purchases >  5
GROUP BY subscription_status

--Q10 : What is the revenue contrubution of each age group??

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC 
